name = "cubagest-backend"
main = "src/index.ts"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "cubagest-db"
database_id = "067cfeb9-8fd8-4dd1-a201-5f874db9977a"

[vars]
ENVIRONMENT = "production"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1


# Secrets (no poner valores aqui, usar wrangler secret put):
# JWT_SECRET
# QVAPAY_APP_ID
# QVAPAY_APP_SECRET
# QVAPAY_CALLBACK_URL
# APP_URL
