-- NOTA HISTÓRICA — este archivo ya NO toca ninguna fecha.
--
-- Qué fue esto: la escritura a mano guardó instantes en MILISEGUNDOS
-- (Date.now()) en columnas que Drizzle lee como SEGUNDOS. Se intentó
-- "arreglar" las filas viejas aquí, primero multiplicando por 1000 y luego
-- (bien entendido el error) se planteó dividir. Ambas direcciones eran
-- peligrosas: el corte del filtro (1e11) no distingue con seguridad un
-- segundo válido de un milisegundo válido en todos los casos, y una fila
-- corregida mal queda corrupta para siempre.
--
-- DECISIÓN (2026-09-29): la base se LIMPIA antes de lanzar a producción, así
-- que no hay filas viejas que rescatar. El UPDATE se eliminó por completo:
-- ninguna migración corrige fechas, y las filas las escriben SIEMPRE
-- correctas el código actual (src/lib/fechas.ts: segundos, siempre) — esa es
-- la reparación real, y la defensa contra regresiones es la sección 21 de
-- scripts/p0_logic_check.mjs, que falla si algún .bind() guarda ms.
--
-- El archivo se conserva (vacío de efectos) porque la cadena de migraciones
-- ya fue aplicada con este nombre; borrarlo del historial rompería
-- `wrangler d1 migrations`. En una base nueva es un no-op.
